version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


  db:
    image: postgres
    env_file:
      - .env.sample
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env.sample
    tty: true
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
