# Generated by Django 4.2.4 on 2024-03-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='подписан'),
        ),
    ]
